# Generated by Django 4.2.29 on 2026-05-12 18:57

import datetime
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('RUNNING', 'Çalışıyor'), ('FEASIBLE', 'Çözüm Bulundu'), ('INFEASIBLE', 'Çözümsüz'), ('FAILED', 'Başarısız'), ('CANCELLED', 'İptal Edildi')], default='DRAFT', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('solver_name', models.CharField(default='Gurobi', max_length=50)),
                ('solver_time_limit_sec', models.PositiveIntegerField(default=60)),
                ('objective_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('mip_gap', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('assigned_task_count', models.PositiveIntegerField(default=0)),
                ('unassigned_task_count', models.PositiveIntegerField(default=0)),
                ('summary', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Optimization Run',
                'verbose_name_plural': 'Optimization Runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanningPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_locked', models.BooleanField(default=False, help_text='Sonuçlar onaylandıysa kilitlenebilir.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_planning_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Planning Period',
                'verbose_name_plural': 'Planning Periods',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SupervisorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supervisor', models.OneToOneField(help_text='Bu grubun sorumlu supervisor kullanıcısı', on_delete=django.db.models.deletion.PROTECT, related_name='supervised_group', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supervisor Group',
                'verbose_name_plural': 'Supervisor Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('operation_type', models.CharField(choices=[('MAINTENANCE', 'Planned Maintenance'), ('CALLBACK', 'Callback / Arıza'), ('FOLLOW_UP', 'Callback Follow-up')], max_length=20)),
                ('required_specialty', models.CharField(choices=[('ELEVATOR', 'Asansör Uzmanı'), ('ESCALATOR', 'Yürüyen Merdiven Uzmanı'), ('BOTH', 'Her İkisi')], default='ELEVATOR', max_length=20)),
                ('required_technician_role', models.CharField(choices=[('MAINTENANCE', 'Bakım Teknisyeni'), ('REPAIR', 'Arıza Teknisyeni'), ('BOTH', 'Her İkisi')], default='MAINTENANCE', max_length=20)),
                ('base_duration_min', models.PositiveIntegerField(help_text='Varsayılan işlem süresi (dakika)')),
                ('sla_target_min', models.PositiveIntegerField(blank=True, help_text='SLA hedef süresi (dakika). Özellikle callback için kullanılabilir.', null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Task Type',
                'verbose_name_plural': 'Task Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=200, verbose_name='Bina/Ünite Adı')),
                ('unit_code', models.CharField(max_length=50, unique=True, verbose_name='Ünite Kodu')),
                ('unit_type', models.CharField(choices=[('ELEVATOR', 'Asansör'), ('ESCALATOR', 'Yürüyen Merdiven')], default='ELEVATOR', max_length=20, verbose_name='Ünite Tipi')),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(default='Istanbul', max_length=100)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-90.000000')), django.core.validators.MaxValueValidator(Decimal('90.000000'))])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-180.000000')), django.core.validators.MaxValueValidator(Decimal('180.000000'))])),
                ('operating_hours_start', models.TimeField(blank=True, default=datetime.time(9, 0), null=True)),
                ('operating_hours_end', models.TimeField(blank=True, default=datetime.time(18, 0), null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'ordering': ['unit_name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('SUP', 'Supervisor'), ('TECH', 'Technician')], max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('tech_role', models.CharField(choices=[('MAINTENANCE', 'Bakım Teknisyeni'), ('REPAIR', 'Arıza Teknisyeni'), ('BOTH', 'Her İkisi')], max_length=20, verbose_name='Görev Tipi')),
                ('specialty', models.CharField(choices=[('ELEVATOR', 'Asansör Uzmanı'), ('ESCALATOR', 'Yürüyen Merdiven Uzmanı'), ('BOTH', 'Her İkisi')], default='ELEVATOR', max_length=20, verbose_name='Uzmanlık Alanı')),
                ('experience_level', models.IntegerField(choices=[(1, 'Junior'), (2, 'Mid'), (3, 'Senior'), (4, 'Expert'), (5, 'Master')], default=1)),
                ('is_available', models.BooleanField(default=True, verbose_name='Genel olarak aktif/müsait mi?')),
                ('is_active_employee', models.BooleanField(default=True)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90.000000')), django.core.validators.MaxValueValidator(Decimal('90.000000'))])),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180.000000')), django.core.validators.MaxValueValidator(Decimal('180.000000'))])),
                ('work_start', models.TimeField(default=datetime.time(9, 0))),
                ('work_end', models.TimeField(default=datetime.time(18, 0))),
                ('daily_capacity_min', models.PositiveIntegerField(default=480, help_text='Dakika bazlı günlük kapasite')),
                ('max_overtime_min', models.PositiveIntegerField(default=60, help_text='İzin verilen maksimum mesai (dakika)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='technicians', to='api.supervisorgroup')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technician_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Technician',
                'verbose_name_plural': 'Technicians',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_no', models.CharField(max_length=50, unique=True, verbose_name='İş Emri No')),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Beklemede'), ('ASSIGNED', 'Atandı'), ('IN_PROGRESS', 'Devam Ediyor'), ('COMPLETED', 'Tamamlandı'), ('CANCELLED', 'İptal Edildi'), ('UNASSIGNED', 'Atanamadı')], default='PENDING', max_length=20)),
                ('priority', models.CharField(blank=True, choices=[('AA', 'AA'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=2, null=True)),
                ('is_follow_up', models.BooleanField(default=False)),
                ('estimated_duration_min', models.PositiveIntegerField(help_text='Bu iş emrine özel tahmini süre (dakika)')),
                ('earliest_start', models.DateTimeField(blank=True, null=True)),
                ('latest_finish', models.DateTimeField(blank=True, null=True)),
                ('release_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_unassigned', models.BooleanField(default=False)),
                ('unassigned_reason', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='api.supervisorgroup')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_tasks', to='api.task')),
                ('planning_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='api.planningperiod')),
                ('task_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='api.tasktype')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.unit')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('sequence_order', models.PositiveIntegerField(default=1)),
                ('travel_time_min', models.PositiveIntegerField(blank=True, null=True)),
                ('travel_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('source', models.CharField(choices=[('AUTO', 'Optimization'), ('MANUAL', 'Manual Override')], default='AUTO', max_length=10)),
                ('is_manual_override', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('optimization_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='api.optimizationrun')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.task')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='api.technician')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'ordering': ['start_time', 'sequence_order'],
            },
        ),
        migrations.AddField(
            model_name='optimizationrun',
            name='planning_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='optimization_runs', to='api.planningperiod'),
        ),
        migrations.AddField(
            model_name='optimizationrun',
            name='triggered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='optimization_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DistanceMatrixCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_meters', models.PositiveIntegerField()),
                ('duration_seconds', models.PositiveIntegerField()),
                ('provider', models.CharField(default='GOOGLE_MAPS', max_length=50)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('destination_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distance_destination_rows', to='api.unit')),
                ('origin_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distance_origin_rows', to='api.unit')),
            ],
            options={
                'verbose_name': 'Distance Matrix Cache',
                'verbose_name_plural': 'Distance Matrix Cache',
            },
        ),
        migrations.CreateModel(
            name='AvailabilityRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Beklemede'), ('APPROVED', 'Onaylandı'), ('REJECTED', 'Reddedildi'), ('CANCELLED', 'İptal Edildi')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_availability_requests', to=settings.AUTH_USER_MODEL)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_requests', to='api.technician')),
            ],
            options={
                'verbose_name': 'Availability Request',
                'verbose_name_plural': 'Availability Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('RUN_OPTIMIZATION', 'Run Optimization'), ('MANUAL_ASSIGN', 'Manual Assign')], max_length=30)),
                ('target_model', models.CharField(max_length=100)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('metadata_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('task', 'optimization_run'), name='unique_task_per_optimization_run'),
        ),
        migrations.AddConstraint(
            model_name='planningperiod',
            constraint=models.UniqueConstraint(fields=('start_date', 'end_date'), name='unique_planning_period_dates'),
        ),
        migrations.AddConstraint(
            model_name='distancematrixcache',
            constraint=models.UniqueConstraint(fields=('origin_unit', 'destination_unit', 'provider'), name='unique_distance_cache_row'),
        ),
    ]
