# Generated by Django 4.2.29 on 2026-05-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktype',
            name='maintenance_type',
            field=models.CharField(blank=True, choices=[('PERIODIC', 'Periyodik Bakım'), ('MONTHLY', 'Aylık Bakım'), ('ANNUAL', 'Yıllık Bakım'), ('REVISION', 'Revizyon Bakımı'), ('INSPECTION', 'Kontrol Bakımı')], help_text='Sadece MAINTENANCE görevleri için bakım tipi', max_length=20, null=True),
        ),
    ]
