# Generated by Django 4.2.29 on 2026-06-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_leaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='competency_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Yetkinlik Kodu'),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='maintenance_type',
            field=models.CharField(blank=True, choices=[('A', 'A Bakımı'), ('B', 'B Bakımı'), ('C', 'C Bakımı')], help_text='Sadece MAINTENANCE görevleri için bakım tipi', max_length=20, null=True),
        ),
    ]
