# Generated by Django 4.2.29 on 2026-06-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_unitmaintenancestate'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='last_location_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='required_technician_role',
            field=models.CharField(choices=[('MAINTENANCE', 'Bakım Teknisyeni'), ('CALLBACK', 'Arıza (Callback) Teknisyeni')], default='MAINTENANCE', max_length=20),
        ),
    ]
